LOAD DATA
CHARACTERSET "UTF8"
INFILE "E:\PycharmProjects\query\sqlldr\cpd.csv"
APPEND INTO TABLE UPL_DCS_CPD_DE
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(TICKET_NO CHAR(20),FIRST_NAME CHAR(41),FULL_NAME CHAR(40),FREQUENT_FLYER_NO_OF_PASSENGER CHAR(40),CREDENTIAL_NO CHAR(40),PASSPORT_NO CHAR(20))